### PR TITLE
Adding an option to choose a font

### PR DESCRIPTION
**Pull request by ylmrx**
Thanks for your awesome work :) I hope you find this patch useful.

### CODE REVIEW

**Comment by nbedos** [comment]
Hey man, thanks for contributing the first pull request :)

I do agree that termtosvg needs a way to customize the font used, but I think it belongs with color themes and should be set by the 'font' resource of Xresources. This way it can be set for both the terminal (xterm, urxvt...) and termtosvg in a single place.

This would probably require the following steps:
- Extracting the 'font' resource from Xresources and parsing it to extract a font name usable with CSS (term.get_configuration)
- A font attribute should probably be added to asciicast._AsciiCastTheme, or maybe a new asciicast v2 record type should be created to include the font name so as to not break compatibility with asciinema (see https://github.com/asciinema/asciinema/blob/develop/doc/asciicast-v2.md#notes-on-compatibility)
- Writing the font to the style portion of the SVG animation, using Deja Vu Sans Mono as a fallback if no font is provided by the theme

One last gotcha: termtosvg uses hardcoded numbers for character cells width and height. I picked those numbers for Deja Vu Sans Mono and a 14 pixels font size, so they are probably not suitable for all fonts. At some point it might be necessary to expose them so that they can be set by the user (or even better, to compute them based on the name of the font, but I can't seem to find a way to do that that gives reliable results)

Let me know if you wish to work on this, or are willing to help testing (I definitely need help for that). In any case I'll probably take a deeper look at this this weekend.

Thanks again

**Comment by ylmrx** [comment]
Hello !
The font as it is set in `.Xresources` isn't always a good option, it will often be set to old PCF (the default `fixed` in xterm (ie lines such as : `*-fixed-100-1-*-*` )), and just won't work in this context ! We can safely use it if they are set to TTF/OTF though.
- AsciiCast feels like the best option if it's used correctly by the renderer.
- The CSS in SVG doesn't feel too good if it can be specified before.
Regarding the size : as we always use monospace font in this context, I had a reliable and satisfying render even with thinner fonts. I didn't bother further.
I'll be happy to test any new version, but can't guarantee a sustained contribution further than a line here and there. I'll check the asciicinema thing though.

Does this looks good to you (before we get a better view with asciicast) ?
```
if('--font'):
  render_with_this_in_css
elif(TTF set in Xresources):
  render_with_this_in_css
else:
  use_default_css
```

**Comment by nbedos** [comment]
I have just released version 0.3.0 which includes the font option.

**Comment by nbedos** [comment]
Don't worry about updating your branch, it's ok. I had to do other changes before including your commits in my tree and I didn't want to bother you with a rebase. Your modifications have been added though the following commit : https://github.com/nbedos/termtosvg/commit/d9307401a06caf45ac5f4532b60847c06c1c840a
Thanks again for contributing!

**Pull request closed without merging**
