### PR TITLE
Bold text rendering support

### PR DESCRIPTION
**Pull request by andyone**
Hi! First, thanks for superb utility!

I found that currently `termtosvg` doesn't support the bold text. It adds styles, but text rendered with normal width.

Now, if the character has bold modification flag it adds `font-weight="bold"` attribute to SVG node.

### CODE REVIEW

**Comment by andyone** [comment]
Ouch! I forgot about tests.

**Comment by andyone** [comment]
All should be fine now 😊

**Comment by andyone** [comment]
> Display the character using a 'bright' color alternative

This is a fallback mechanism for terminals which don't support bold fonts (some old ones). At this moment according to [this page](https://misc.flogisoft.com/bash/tip_colors_and_formatting#terminals_compatibility), only Eterm render bold text using bright colors.

Rendering bold text using bright colors it's a real problem if you want to use light colors and bold text at the same time (like me).

> Maybe using a bold font if the color palette does not include bright colors, and use bright colors otherwise?

I think termtosvg should avoid rendering bold colors using bright colors. It's a very old trick for terminals which nobody uses nowadays.

**Comment by nbedos** [comment]
> I think termtosvg should avoid rendering bold text using bright colors. It's a very old trick for terminals which nobody uses nowadays.

I'm relying on bright colors for my own color theme so it would be nice if my own tool could handle them. :D Urxvt (which I'm using) displays bold characters using a bold font and a bright color so that's probably the right thing to do. I didn't notice this earlier because I have disable the bold font in my configuration. Your patch allows 
- having bold characters without bright colors (using an 8 color theme)
- having bold characters with bright colors (define a 16 color theme)

So it should make everyone happy, except maybe people who don't want a bold font. I'd rather not clutter the configuration file with unused options so I'll consider this later if it's requested.

**Pull request closed without merging**
