### PR TITLE
edit a sentence in README.d

### PR DESCRIPTION
**Pull request by melongbob**
- The sentence was broken down to convey one idea per sentence.
- "attempts at terminal recording" -> "terminal recorder"
   The use of the word "attempt" makes the sentence wordier. Also, using "attempt" implies that asciinema is not a proper terminal recorder.

### CODE REVIEW

**Comment by nbedos** [comment]
Thanks for helping! "other terminal recorder" or "other terminal recorder**s**" ?

**Comment by melongbob** [comment]
you are right! I guess it should be "other terminal recorders" :)

**Comment by nbedos** [comment]
Thanks!

**Comment by poch345** [comment]
#38

**Pull request merged**
