### PR TITLE
Ship manuals and tests with package

### PR DESCRIPTION
**Pull request by polyzen**

### CODE REVIEW

**Comment by nbedos** [comment]
Thanks for the pull request. What's the rationale behind these changes? 
Manual pages could be included in the package but pip won't install them in the proper location.
What's the use of having test cases in the package?

**Comment by polyzen** [comment]
So one could run the tests and install the manual pages, specifically as part of building a distro package:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=termtosvg

Eg. https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=xandikos

**Comment by nbedos** [comment]
I see! Thanks for working on the AUR package.

I've included all tests in the package and I've also set up a test suite so that all tests can be run with `python -m unittest termtosvg.tests.suite`. 

Does that look good?

**Comment by polyzen** [comment]
Even better! Wish more projects utilized the test suite feature.

**Comment by nbedos** [comment]
Merged, thanks again! Let me know if you're facing problem with packaging.

**Comment by polyzen** [comment]
Would you be willing to do a patch release for this?

**Comment by eli-schwartz** [comment]
Generally speaking, one is supposed to have the testsuite run in the source tree, not install it as end-user code.

**Comment by polyzen** [comment]
```
>>> print(os.getcwd())
/home/user/.vim/plugged/vim-rst-sections/ftplugin/vim_bridge
>>> import vim_bridge.registry
>>>
```

**Pull request merged**
